server:
  port: 8081

# ---------- DB ----------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservicedb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

